config/routes.rb
Bitodo::Application.routes.draw do
  resources :tasks do
  member do
    patch :complete
  end
end
  root 'tasks#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
 validates :title, presence: true
 validates :priority, inclusion: { in: %w(low medium HIGH), message: "wrong %{value}" }


def self.search(search,type)
if search
    case type
        when "done?"
                where('completed IS NULL')
        when "title"
                where('title LIKE ?', "%#{search}%")
        when "text tag"
                where('text LIKE ?', "%#{search}%")
        when "till date"                                
                where('time LIKE ?', "%#{search}%")
        when "priority"
                where('priority LIKE ?', "%#{search}%")
    end
else
    scoped
end        

end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    if params[:search]
      @tasks = Task.search(params[:search],params[:fieldtype])
    else
      @tasks = Task.all
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def complete
    @task = Task.find(params[:id])
    @task.update_attribute(:completed, Time.now)
    redirect_to tasks_path, notice: 'Task was successfully updated.' 
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :text, :time, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bitodo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "text tag" %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label "deadline" %><br>
    <%= f.date_select :time %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.select(:priority, %w[low medium HIGH]) %>

  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-default" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container well">
<h1>Edit task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

</div>

app/views/tasks/index.html.erb
<div class="container">
<div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
        <div class="col-md-4">
            <h1><span class="glyphicon glyphicon-check"></span> ToDo</h1>
            <p>BitTOdO app</p>
        </div>
        <div class="col-md-4 pull-right">
          <br>
          <br>
            <%= form_tag('/tasks', method: :get) do %>
            <%= text_field_tag :search %>
            <%= select_tag "fieldtype", options_for_select(["title", "text tag", "till date", "priority" ], "done?") %>
            <%= submit_tag "filter" , class:"btn btn-default" %>
            <% end %>
            <%= form_tag('/tasks', method: :get) do %>
            <%= hidden_field_tag(:search) %>
            <%= hidden_field_tag "fieldtype", "done?" %>
            <%= submit_tag "show work ToDo", class:"btn btn-warning" %>
            <% end %>
        </div>
      </div>
</div>
<div class="panel-body">
<table class="table">
  <thead>
    <tr>
      <th>DOne</th>
      <th>Title</th>
      <th>Text tag</th>
      <th>Till Date</th>
      <th>Priority</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
        <% if !task.completed.blank? %>
        <tr class="bg-success">
        <td><%= task.completed.strftime("%d %b %Y %H:%M")  %></td>
        <% end %>
        <% if task.completed.blank? %>
        <tr>
        <td><%= link_to 'Done?', complete_task_path(task), method: :patch, class:"label label-danger" %></td>
        <% end %>
        <td><%= link_to task.title, task %></td>
        <td><%= task.text %></td>
        <td><%= task.time.strftime("%d %b %Y") %></td>
        <td><%= task.priority %></td>
        <td><%= link_to  raw('<span class="glyphicon glyphicon-pencil"></span>'), edit_task_path(task) %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-remove"></span>'), task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<div class="panel-footer">
<%= link_to 'New Task', new_task_path, class:"btn btn-default" %>
<%= link_to 'All Tasks', tasks_path, class:"btn btn-default" %></div>
</div>


</div>

app/views/tasks/new.html.erb
<div class="container well">

<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path, class:"btn btn-default" %>

</div>

app/views/tasks/show.html.erb
<div class="container well">

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @task.text %>
</p>

<p>
  <strong>Time:</strong>
  <%= @task.time %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/unfinished.html.erb
<div class="container">
<div class="panel panel-default">
      <div class="panel-heading">
            <h1>ToDo</h1>
                    <p>BitTOdO app</p>
          </div>
<div class="panel-body">
<table class="table table-striped">
  <thead>
    <tr>
      <th>DOne</th>
      <th>Title</th>
      <th>Text</th>
      <th>Till Date</th>
      <th>Priority</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <% if !task.completed.blank? %>
        <td><%= task.completed %></td>
        <% end %>
        <% if task.completed.blank? %>
        <td><%= link_to 'Done?', complete_task_path(task), method: :patch, class:"label label-danger" %></td>
        <% end %>
        <td><%= task.title %></td>
        <td><%= task.text %></td>
        <td><%= task.time %></td>
        <td><%= task.priority %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>

<%= link_to 'New Task', new_task_path, class:"btn btn-default" %>

</div>